# Generated by Django 5.1.7 on 2026-05-26 06:04

import login.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('Username', models.CharField(default='', error_messages='Max length of username is 16 characters', max_length=16)),
                ('userMail', models.EmailField(default='', max_length=254, unique=True)),
                ('userpassword', models.BinaryField(default=0, validators=[login.models.check])),
                ('user_interest', models.JSONField(default=list)),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_wishlist', models.JSONField(default=list)),
                ('user_blog', models.JSONField(default=list)),
            ],
        ),
    ]
